### ISSUE TITLE
FileField bug?

### ISSUE THREAD

**Issue by miguxbe** [krafthaus/bauhaus#44]
I am getting some errors with the last commit. The log error: ******/vendor/krafthaus/bauhaus/src/KraftHaus/Bauhaus/Field/FileField.php:92 

The file uploading stops working :( . I am using the interface in this way :        
$mapper->file('file')->location('public/uploads/images')->naming('random');

**Comment by thatonefreeman** [comment]
Hello, I ran into this issue as well. Add the following line: 
"use Illuminate\Support\Facades\View;"

to vendor/krafthaus/bauhaus/src/KraftHaus/Bauhaus/Field/DateField.php

**Comment by miguxbe** [comment]
Thanks @thatonefreeman.
