### ISSUE TITLE
configureForm($mapper)  not render fields

### ISSUE THREAD

**Issue by milantestagena** [krafthaus/bauhaus#69]
Hi

I created this:
public function configureForm($mapper) {
        $mapper->text('title')->label('Post title');
	$mapper->wysiwyg('content');
    }
from Post tutorial.

on admin post page, when i click New post, I don't have those 2 fields. I only have Create Post button. 
When I click on that button, it add new Post, with empty data.

what I need to do to get those 2 fields in Admin panel?

thanx

**Comment by milantestagena** [comment]
Fixed

please delete this thread.
thanx

**Comment by tholu** [comment]
You can mark as closed.
